options:
  openstack-origin:
    default: juno
    type: string
    description: |
      Version of Openstack nova compute to install. Choices are:
      - icehouse
      - juno
  installer-url:
    type: string
    description: |
      overwrite default installer location. Take care to set correct openstack-origin
      as that will be used by the charm to pick the correct config templates.
  ovs-installer-url:
    type: string
    description: |
      Location of the OVS MSI installer
  rabbit-user:
    default: nova
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    decsription: Rabbitmq vhost
  multi-host:
    default: "yes"
    type: string
    description: Whether to run nova-api and nova-network on the compute nodes.
  enable-live-migration:
    default: False
    type: boolean
    description: Configure Hyper-V for live migration.
  migration-auth-type:
    default: CredSSP
    type: string
    description: |
      TCP authentication scheme for Hyper-V live migration.  Available options
      include CredSSP or Kerberos. (Not yet implemented)
  data-port:
    type: string
    description: |
      Ethernet inerface to use for vmswitch. This can be a MAC address or an interface name.
      This option is mandatory if more then one interface is present on the target system.
      In cases where there is only one interface on the system, the vmswitch will be created using that
      interface and OSManagement will be set to True, regardless of the vmswitch-management option.
      Avoid using the management interface as a data interface where system has more then one NIC.
  data-port-vlan:
    default: 8
    type: int
    description: |
      VLAN over which tunnels should be made
  bond-ports:
    type: string
    description: |
      MAC addresses of ports participating in bond link
  network-type:
    type: string
    default: hyperv
    description: |
      Neutron agent to use. Valid options are:
        * hyperv
        * ovs
      Default is hyperv
  vmswitch-name:
    default: br100
    type: string
    description: Virtual switch to use
  vmswitch-management:
    default: False
    type: boolean
    description: |
      Allow management OS on this vm switch. If True, the switch will be set in DHCP mode.
  log-dir:
    default: C:\OpenStack\Log
    type: string
    description: |
      Log folder location
  instances-dir:
    default: C:\OpenStack\Instances
    type: string
    decription: |
      Location in which to store VM disks
  install-local-packages:
    default: False
    type: boolean
    description: |
      This is a hack. It tells the charm to install nova and neutron from local tar archive
  local-ip-pool:
    type: string
    description: |
      Use this for local Ip range
